// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-5ImCY8_-DyvSH2XAwo3A9LwAv4-2ydo',
    appId: '1:272987068622:web:34d8964200883957e0589f',
    messagingSenderId: '272987068622',
    projectId: 'weatherapp-c634e',
    authDomain: 'weatherapp-c634e.firebaseapp.com',
    storageBucket: 'weatherapp-c634e.firebasestorage.app',
    measurementId: 'G-9YWXBP09TG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVdVkaAT74XW0M24FHwU_u0eRn-rmTJ6Y',
    appId: '1:272987068622:android:18cc28b134210c5be0589f',
    messagingSenderId: '272987068622',
    projectId: 'weatherapp-c634e',
    storageBucket: 'weatherapp-c634e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3kiuExeWLwyHUMiVI_ZWxLEapTbMVKH8',
    appId: '1:272987068622:ios:323db587843ace20e0589f',
    messagingSenderId: '272987068622',
    projectId: 'weatherapp-c634e',
    storageBucket: 'weatherapp-c634e.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3kiuExeWLwyHUMiVI_ZWxLEapTbMVKH8',
    appId: '1:272987068622:ios:323db587843ace20e0589f',
    messagingSenderId: '272987068622',
    projectId: 'weatherapp-c634e',
    storageBucket: 'weatherapp-c634e.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-5ImCY8_-DyvSH2XAwo3A9LwAv4-2ydo',
    appId: '1:272987068622:web:080a7364b8a5ed55e0589f',
    messagingSenderId: '272987068622',
    projectId: 'weatherapp-c634e',
    authDomain: 'weatherapp-c634e.firebaseapp.com',
    storageBucket: 'weatherapp-c634e.firebasestorage.app',
    measurementId: 'G-VTZ7RG67TQ',
  );
}
